spring:
  application:
    name: trip-hotel-service
  data:
    mongodb:
      uri: mongodb://root:fudanse@localhost:27017
      database: hotel_db

server:
  port: 24214

grpc:
  server:
    port: 50054
    address: 0.0.0.0