spring:
  application:
    name: trip-itinerary-service
  cloud:
    nacos:
      server-addr: localhost:8848
  data:
    mongodb:
      uri: mongodb://root:fudanse@localhost:27017
      database: itinerary_db

server:
  port: 24219

grpc:
  server:
    port: 50052
    enable-reflection: true

logging:
  level:
    org.tripsphere.itinerary: DEBUG
    net.devh.boot.grpc: INFO